### ISSUE TITLE
Sydowh commit 

### ISSUE THREAD

**Issue by DoctorFitch** [DoctorFitch/FORMA#1]
Here some code u cn insert in your git shell my friend :
* $ git add .
* $ git push -u origin master

**Comment by Sydowh** [comment]
Thanks a lot bro, u real mate i mirin

**Comment by DoctorFitch** [comment]
Oh fak, ur a zyzz bru ?

**Comment by Sydowh** [comment]
no i just mirin gainz brah, i m a fucking shredded sickunt

**Comment by DoctorFitch** [comment]
same culture, same blood #prayforgainz

**Comment by Sydowh** [comment]
yay real sentence bruh i mirin
